sudo: required
dist: xenial
language: python
python: '3.5'
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build
env:
 - DISTS_VM=fc29 USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=fc30 USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=buster USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=centos7 USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1

jobs:
  include:
    - python: '3.5'
      install: pip install --quiet -r ci/requirements.txt
      env: TESTS_ONLY=1
      script:
       - ./run-tests
       - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
      after_success:
       - codecov
    - stage: deploy
      python: '3.5'
      env: DIST_DOM0=fc29 TESTS_ONLY=
      script: ~/qubes-builder/scripts/travis-deploy


branches:
  except:
    - /.*_.*/
    - build
